[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string]$AppRoot,

  [Parameter(Mandatory = $true)]
  [string]$BackendRoot,

  [string]$LogPath
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 3.0

. (Join-Path $PSScriptRoot 'fatboy-installer.config.ps1')
$Config = $script:FatboyInstallerConfig

if (-not $LogPath) {
  $LogPath = Join-Path $AppRoot $Config.DatabaseLogRelativePath
}

function Write-DbLog {
  param([string]$Message)
  $line = "[{0}] {1}" -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss'), $Message
  $dir = Split-Path $LogPath -Parent
  if ($dir) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  Add-Content -Path $LogPath -Value $line -Encoding UTF8
  Write-Host $line
}

function New-SafePassword {
  param([int]$Bytes = 24)
  $raw = [byte[]]::new($Bytes)
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($raw)
  return [Convert]::ToBase64String($raw).Replace('+', 'A').Replace('/', 'B').TrimEnd('=')
}

function ConvertTo-DatabaseUrlPassword {
  param([Parameter(Mandatory = $true)][string]$Value)
  return [System.Uri]::EscapeDataString($Value)
}

function Get-DatabaseUrlParts {
  param([string]$DatabaseUrl)
  if (-not $DatabaseUrl) { return $null }
  try {
    $uri = [System.Uri]$DatabaseUrl
    if ($uri.Scheme -ne 'postgresql' -and $uri.Scheme -ne 'postgres') { return $null }
    $userInfo = $uri.UserInfo -split ':', 2
    return @{
      Host = $uri.Host
      Port = if ($uri.Port -gt 0) { $uri.Port } else { 5432 }
      Database = $uri.AbsolutePath.TrimStart('/')
      User = [System.Uri]::UnescapeDataString($userInfo[0])
      Password = if ($userInfo.Count -gt 1) { [System.Uri]::UnescapeDataString($userInfo[1]) } else { '' }
    }
  } catch {
    return $null
  }
}

function Read-DotEnv {
  param([string]$Path)
  $result = [ordered]@{}
  if (-not (Test-Path -LiteralPath $Path)) { return $result }

  foreach ($line in Get-Content -LiteralPath $Path -Encoding UTF8) {
    if ($line -match '^\s*#' -or $line -notmatch '=') { continue }
    $parts = $line -split '=', 2
    $key = $parts[0].Trim()
    $value = $parts[1].Trim()
    if ($value.Length -ge 2 -and (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'")))) {
      $value = $value.Substring(1, $value.Length - 2)
    }
    if ($key) { $result[$key] = $value }
  }
  return $result
}

function Write-DotEnv {
  param(
    [string]$Path,
    [System.Collections.IDictionary]$Values
  )
  $dir = Split-Path $Path -Parent
  if ($dir) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }

  $orderedKeys = @(
    'DATABASE_URL',
    'JWT_SECRET',
    'JWT_EXPIRES_IN',
    'PORT',
    'NODE_ENV',
    'FATBOY_BACKEND_ROOT',
    'FATBOY_APP_ROOT',
    'FATBOY_POSTGRES_HOST',
    'FATBOY_POSTGRES_PORT',
    'FATBOY_POSTGRES_DATABASE',
    'FATBOY_POSTGRES_APP_USER',
    'FATBOY_POSTGRES_SERVICE_NAME'
  )

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('# Fatboy POS Backend runtime configuration')
  $lines.Add('# Generated by the Fatboy POS Backend installer. Re-run installer to repair/update.')

  foreach ($key in $orderedKeys) {
    if ($Values.ContainsKey($key)) {
      $escaped = [string]$Values[$key]
      $lines.Add('{0}="{1}"' -f $key, $escaped.Replace('"', '\"'))
    }
  }

  foreach ($key in ($Values.Keys | Sort-Object)) {
    if ($orderedKeys -contains $key) { continue }
    $escaped = [string]$Values[$key]
    $lines.Add('{0}="{1}"' -f $key, $escaped.Replace('"', '\"'))
  }

  Set-Content -Path $Path -Value $lines -Encoding UTF8
}

function Find-Psql {
  $candidates = New-Object System.Collections.Generic.List[string]
  $cmd = Get-Command psql.exe -ErrorAction SilentlyContinue
  if ($cmd) { $candidates.Add($cmd.Source) }

  $programFiles = @($env:ProgramFiles, ${env:ProgramFiles(x86)}) | Where-Object { $_ }
  foreach ($base in $programFiles) {
    $pgRoot = Join-Path $base 'PostgreSQL'
    if (Test-Path -LiteralPath $pgRoot) {
      Get-ChildItem -LiteralPath $pgRoot -Filter psql.exe -Recurse -ErrorAction SilentlyContinue |
        ForEach-Object { $candidates.Add($_.FullName) }
    }
  }

  $managed = Join-Path $AppRoot $Config.PostgresInstallDirName
  $managedPsql = Join-Path $managed 'bin\psql.exe'
  if (Test-Path -LiteralPath $managedPsql) { $candidates.Add($managedPsql) }

  return $candidates | Select-Object -Unique | Select-Object -First 1
}

function Test-TcpPort {
  param([string]$HostName, [int]$Port)
  try {
    $client = [System.Net.Sockets.TcpClient]::new()
    $async = $client.BeginConnect($HostName, $Port, $null, $null)
    if (-not $async.AsyncWaitHandle.WaitOne(1200)) {
      $client.Close()
      return $false
    }
    $client.EndConnect($async)
    $client.Close()
    return $true
  } catch {
    return $false
  }
}

function Invoke-Psql {
  param(
    [Parameter(Mandatory = $true)][string]$PsqlPath,
    [Parameter(Mandatory = $true)][string]$Database,
    [Parameter(Mandatory = $true)][string]$User,
    [Parameter(Mandatory = $true)][string]$Password,
    [Parameter(Mandatory = $true)][string]$Sql,
    [string]$HostName = $Config.PostgresHost,
    [int]$Port = $Config.PostgresPort
  )

  $env:PGPASSWORD = $Password
  try {
    $output = & $PsqlPath `
      --host $HostName `
      --port $Port `
      --username $User `
      --dbname $Database `
      --no-password `
      --no-psqlrc `
      --set ON_ERROR_STOP=1 `
      --tuples-only `
      --command $Sql 2>&1
    $code = $LASTEXITCODE
  } finally {
    Remove-Item Env:\PGPASSWORD -ErrorAction SilentlyContinue
  }

  if ($code -ne 0) {
    throw "psql fallo con codigo $code. Salida: $($output -join [Environment]::NewLine)"
  }

  return ($output -join [Environment]::NewLine).Trim()
}

function Test-PostgresLogin {
  param(
    [string]$PsqlPath,
    [string]$HostName,
    [int]$Port,
    [string]$Database,
    [string]$User,
    [string]$Password
  )

  if (-not $PsqlPath -or -not (Test-TcpPort -HostName $HostName -Port $Port)) { return $false }
  try {
    Invoke-Psql -PsqlPath $PsqlPath -HostName $HostName -Port $Port -Database $Database -User $User -Password $Password -Sql 'select 1;' | Out-Null
    return $true
  } catch {
    Write-DbLog "Conexion PostgreSQL no utilizable para $User@$HostName`:$Port/${Database}: $($_.Exception.Message)"
    return $false
  }
}

function Get-PostgresInstallerPath {
  $offlinePath = Join-Path $AppRoot ("payload\postgresql\" + $Config.PostgresInstallerFile)
  if (Test-Path -LiteralPath $offlinePath) {
    Write-DbLog "Usando instalador offline de PostgreSQL: $offlinePath"
    return $offlinePath
  }

  $cacheDir = Join-Path $AppRoot 'payload\postgresql'
  New-Item -ItemType Directory -Path $cacheDir -Force | Out-Null
  $downloadPath = Join-Path $cacheDir $Config.PostgresInstallerFile
  if (Test-Path -LiteralPath $downloadPath) { return $downloadPath }

  Write-DbLog "Descargando PostgreSQL desde $($Config.PostgresDownloadUrl)"
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  Invoke-WebRequest -Uri $Config.PostgresDownloadUrl -OutFile $downloadPath -UseBasicParsing
  return $downloadPath
}

function Install-ManagedPostgres {
  param([string]$SuperPassword)

  $installer = Get-PostgresInstallerPath
  $installDir = Join-Path $AppRoot $Config.PostgresInstallDirName
  $dataDir = Join-Path $AppRoot $Config.PostgresDataDirName
  New-Item -ItemType Directory -Path $installDir -Force | Out-Null
  New-Item -ItemType Directory -Path $dataDir -Force | Out-Null

  $args = @(
    '--mode', 'unattended',
    '--unattendedmodeui', 'none',
    '--superpassword', $SuperPassword,
    '--servicename', $Config.PostgresServiceName,
    '--serverport', [string]$Config.PostgresPort,
    '--prefix', $installDir,
    '--datadir', $dataDir,
    '--locale', 'C',
    '--disable-components', 'stackbuilder'
  )

  Write-DbLog "Instalando PostgreSQL administrado por Fatboy POS en $installDir"
  & $installer @args
  if ($LASTEXITCODE -ne 0) {
    throw "Instalador PostgreSQL fallo con codigo $LASTEXITCODE"
  }

  $service = Get-Service -Name $Config.PostgresServiceName -ErrorAction SilentlyContinue
  if ($service) {
    Set-Service -Name $Config.PostgresServiceName -StartupType Automatic
    if ($service.Status -ne 'Running') {
      Start-Service -Name $Config.PostgresServiceName
    }
  }

  $deadline = (Get-Date).AddSeconds(60)
  while ((Get-Date) -lt $deadline) {
    if (Test-TcpPort -HostName $Config.PostgresHost -Port $Config.PostgresPort) { return }
    Start-Sleep -Seconds 1
  }

  throw "PostgreSQL instalado pero no responde en $($Config.PostgresHost):$($Config.PostgresPort)"
}

function Ensure-DatabaseAndUser {
  param(
    [string]$PsqlPath,
    [string]$SuperPassword,
    [string]$AppPassword
  )

  $hostName = $Config.PostgresHost
  $port = [int]$Config.PostgresPort
  $db = $Config.PostgresDatabase
  $appUser = $Config.PostgresAppUser
  $escapedAppPassword = $AppPassword.Replace("'", "''")

  $roleExists = Invoke-Psql -PsqlPath $PsqlPath -HostName $hostName -Port $port -Database 'postgres' -User $Config.PostgresSuperUser -Password $SuperPassword -Sql "select 1 from pg_roles where rolname = '$appUser';"
  if (-not $roleExists) {
    Invoke-Psql -PsqlPath $PsqlPath -HostName $hostName -Port $port -Database 'postgres' -User $Config.PostgresSuperUser -Password $SuperPassword -Sql "create role $appUser with login password '$escapedAppPassword';"
    Write-DbLog "Usuario PostgreSQL creado: $appUser"
  } else {
    Invoke-Psql -PsqlPath $PsqlPath -HostName $hostName -Port $port -Database 'postgres' -User $Config.PostgresSuperUser -Password $SuperPassword -Sql "alter role $appUser with login password '$escapedAppPassword';"
    Write-DbLog "Usuario PostgreSQL actualizado: $appUser"
  }

  $dbExists = Invoke-Psql -PsqlPath $PsqlPath -HostName $hostName -Port $port -Database 'postgres' -User $Config.PostgresSuperUser -Password $SuperPassword -Sql "select 1 from pg_database where datname = '$db';"
  if (-not $dbExists) {
    Invoke-Psql -PsqlPath $PsqlPath -HostName $hostName -Port $port -Database 'postgres' -User $Config.PostgresSuperUser -Password $SuperPassword -Sql "create database $db owner $appUser;"
    Write-DbLog "Base de datos creada: $db"
  } else {
    Invoke-Psql -PsqlPath $PsqlPath -HostName $hostName -Port $port -Database 'postgres' -User $Config.PostgresSuperUser -Password $SuperPassword -Sql "alter database $db owner to $appUser;"
    Write-DbLog "Base de datos existente verificada: $db"
  }

  Invoke-Psql -PsqlPath $PsqlPath -HostName $hostName -Port $port -Database $db -User $Config.PostgresSuperUser -Password $SuperPassword -Sql "grant all privileges on database $db to $appUser; grant all on schema public to $appUser; alter schema public owner to $appUser;"
}

function Invoke-EmbeddedNode {
  param(
    [Parameter(Mandatory = $true)][string[]]$Arguments,
    [string]$WorkingDirectory = $BackendRoot
  )
  $node = Join-Path $AppRoot 'node\node.exe'
  if (-not (Test-Path -LiteralPath $node)) { throw "No existe Node embebido: $node" }

  Push-Location $WorkingDirectory
  try {
    & $node @Arguments
    if ($LASTEXITCODE -ne 0) {
      throw "Node fallo con codigo ${LASTEXITCODE}: $($Arguments -join ' ')"
    }
  } finally {
    Pop-Location
  }
}

function Invoke-PrismaDeploy {
  $prismaCli = Join-Path $BackendRoot 'node_modules\prisma\build\index.js'
  if (-not (Test-Path -LiteralPath $prismaCli)) {
    throw "No existe Prisma CLI en el paquete: $prismaCli"
  }

  Write-DbLog 'Ejecutando Prisma migrate deploy'
  Invoke-EmbeddedNode -Arguments @($prismaCli, 'migrate', 'deploy', '--schema', (Join-Path $BackendRoot 'prisma\schema.prisma'))
}

function Invoke-SeedIfNeeded {
  $seedJs = Join-Path $BackendRoot 'dist\prisma\seed.js'
  if (-not (Test-Path -LiteralPath $seedJs)) {
    Write-DbLog "Seed compilado no encontrado; se omite: $seedJs"
    return
  }

  Write-DbLog 'Ejecutando seed idempotente compilado'
  Invoke-EmbeddedNode -Arguments @($seedJs)
}

function Initialize-FatboyPostgres {
  $envPath = Join-Path $AppRoot $Config.EnvFileRelativePath
  $existingEnv = Read-DotEnv -Path $envPath
  $existingDatabaseUrl = if ($existingEnv.Contains('DATABASE_URL')) { $existingEnv['DATABASE_URL'] } else { $null }
  $existingDb = Get-DatabaseUrlParts -DatabaseUrl $existingDatabaseUrl
  $superPassword = if ($existingEnv.Contains('FATBOY_POSTGRES_SUPER_PASSWORD')) { $existingEnv['FATBOY_POSTGRES_SUPER_PASSWORD'] } else { New-SafePassword }
  $appPassword = if ($existingEnv.Contains('FATBOY_POSTGRES_APP_PASSWORD')) { $existingEnv['FATBOY_POSTGRES_APP_PASSWORD'] } else { New-SafePassword }
  $jwtSecret = if ($existingEnv.Contains('JWT_SECRET')) { $existingEnv['JWT_SECRET'] } else { New-SafePassword -Bytes 48 }

  $psql = Find-Psql

  if ($existingDb -and $psql -and -not $env:FATBOY_FORCE_MANAGED_POSTGRES) {
    Write-DbLog "Validando DATABASE_URL existente para reutilizacion segura."
    if (Test-PostgresLogin -PsqlPath $psql -HostName $existingDb.Host -Port ([int]$existingDb.Port) -Database $existingDb.Database -User $existingDb.User -Password $existingDb.Password) {
      $envValues = [ordered]@{}
      foreach ($key in $existingEnv.Keys) { $envValues[$key] = $existingEnv[$key] }
      $envValues['DATABASE_URL'] = $existingDatabaseUrl
      $envValues['JWT_SECRET'] = $jwtSecret
      $envValues['JWT_EXPIRES_IN'] = if ($existingEnv.Contains('JWT_EXPIRES_IN')) { $existingEnv['JWT_EXPIRES_IN'] } else { '1d' }
      $envValues['PORT'] = [string]$Config.BackendPort
      $envValues['NODE_ENV'] = 'production'
      $envValues['FATBOY_BACKEND_ROOT'] = $BackendRoot
      $envValues['FATBOY_APP_ROOT'] = $AppRoot
      $envValues['FATBOY_POSTGRES_HOST'] = $existingDb.Host
      $envValues['FATBOY_POSTGRES_PORT'] = [string]$existingDb.Port
      $envValues['FATBOY_POSTGRES_DATABASE'] = $existingDb.Database
      $envValues['FATBOY_POSTGRES_APP_USER'] = $existingDb.User
      $envValues['FATBOY_POSTGRES_SERVICE_NAME'] = if ($existingEnv.Contains('FATBOY_POSTGRES_SERVICE_NAME')) { $existingEnv['FATBOY_POSTGRES_SERVICE_NAME'] } else { 'external-postgresql' }

      Write-DotEnv -Path $envPath -Values $envValues
      Write-DbLog 'PostgreSQL existente reutilizado; se aplicaran migraciones sobre DATABASE_URL actual.'
      Invoke-PrismaDeploy
      Invoke-SeedIfNeeded
      Invoke-Psql -PsqlPath $psql -HostName $existingDb.Host -Port ([int]$existingDb.Port) -Database $existingDb.Database -User $existingDb.User -Password $existingDb.Password -Sql 'select count(*) from information_schema.tables where table_schema = ''public'';' | Out-Null
      Write-DbLog 'PostgreSQL existente validado correctamente.'
      return
    }
  }

  $canUseExisting = $false

  if ($psql) {
    Write-DbLog "psql detectado: $psql"
    $canUseExisting = Test-PostgresLogin -PsqlPath $psql -HostName $Config.PostgresHost -Port ([int]$Config.PostgresPort) -Database 'postgres' -User $Config.PostgresSuperUser -Password $superPassword
  }

  if (-not $canUseExisting) {
    $service = Get-Service -Name $Config.PostgresServiceName -ErrorAction SilentlyContinue
    if (-not $service) {
      Install-ManagedPostgres -SuperPassword $superPassword
    } elseif ($service.Status -ne 'Running') {
      Start-Service -Name $Config.PostgresServiceName
    }

    $psql = Find-Psql
    if (-not $psql) { throw 'No se encontro psql.exe despues de instalar PostgreSQL.' }
  }

  if (-not (Test-PostgresLogin -PsqlPath $psql -HostName $Config.PostgresHost -Port ([int]$Config.PostgresPort) -Database 'postgres' -User $Config.PostgresSuperUser -Password $superPassword)) {
    throw 'PostgreSQL no acepta conexion administrativa; no se puede configurar la base de datos de forma segura.'
  }

  Ensure-DatabaseAndUser -PsqlPath $psql -SuperPassword $superPassword -AppPassword $appPassword

  $databaseUrl = 'postgresql://{0}:{1}@{2}:{3}/{4}' -f `
    $Config.PostgresAppUser,
    (ConvertTo-DatabaseUrlPassword $appPassword),
    $Config.PostgresHost,
    $Config.PostgresPort,
    $Config.PostgresDatabase

  $envValues = [ordered]@{}
  foreach ($key in $existingEnv.Keys) { $envValues[$key] = $existingEnv[$key] }
  $envValues['DATABASE_URL'] = $databaseUrl
  $envValues['JWT_SECRET'] = $jwtSecret
  $envValues['JWT_EXPIRES_IN'] = if ($existingEnv.Contains('JWT_EXPIRES_IN')) { $existingEnv['JWT_EXPIRES_IN'] } else { '1d' }
  $envValues['PORT'] = [string]$Config.BackendPort
  $envValues['NODE_ENV'] = 'production'
  $envValues['FATBOY_BACKEND_ROOT'] = $BackendRoot
  $envValues['FATBOY_APP_ROOT'] = $AppRoot
  $envValues['FATBOY_POSTGRES_HOST'] = $Config.PostgresHost
  $envValues['FATBOY_POSTGRES_PORT'] = [string]$Config.PostgresPort
  $envValues['FATBOY_POSTGRES_DATABASE'] = $Config.PostgresDatabase
  $envValues['FATBOY_POSTGRES_APP_USER'] = $Config.PostgresAppUser
  $envValues['FATBOY_POSTGRES_APP_PASSWORD'] = $appPassword
  $envValues['FATBOY_POSTGRES_SUPER_PASSWORD'] = $superPassword
  $envValues['FATBOY_POSTGRES_SERVICE_NAME'] = $Config.PostgresServiceName

  Write-DotEnv -Path $envPath -Values $envValues
  Write-DbLog "Archivo de entorno escrito: $envPath"

  Invoke-PrismaDeploy
  Invoke-SeedIfNeeded

  if (-not (Test-PostgresLogin -PsqlPath $psql -HostName $Config.PostgresHost -Port ([int]$Config.PostgresPort) -Database $Config.PostgresDatabase -User $Config.PostgresAppUser -Password $appPassword)) {
    throw 'La conexion final con usuario de aplicacion fallo.'
  }

  Invoke-Psql -PsqlPath $psql -HostName $Config.PostgresHost -Port ([int]$Config.PostgresPort) -Database $Config.PostgresDatabase -User $Config.PostgresAppUser -Password $appPassword -Sql 'select count(*) from information_schema.tables where table_schema = ''public'';' | Out-Null
  Write-DbLog 'PostgreSQL configurado y validado correctamente.'
}

Initialize-FatboyPostgres
